import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";
import React from "react";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/mode-toggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{children:React.ReactNode}> = (
  {children}
) => {

return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
      >
      <SidebarProvider>
        <AppSidebar/>
        <div className="flex flex-col w-full">
          <div className="flex flex-row justify-between p-2">
            <SidebarTrigger/>
            <ModeToggle/>
          </div>
          <div className="p-8">
            {children}
          </div>
        </div>
      </SidebarProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout
